version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  install-node:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '19.8.1'
      - run: node --version

  install-deps:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: 'Install npm'
          command: 'apk add npm'
      - run:
          name: 'Install dependencies'
          command: 'npm install'

workflows:
  say-hello-workflow:
    jobs:
      - install-node
      - install-deps
