version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:19.8.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
  run_lint:
    steps:
      - checkout
      - run:
          name: Run lint
          command: npm run lint
  run_tests:
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run test

workflows:
  my_wordlist_mobile_workflow:
    jobs:
      - install_dependencies
      - run_lint
      - run_tests
