version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  test:
    executor: node/default
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          node-version: '19.8.1'
      - run:
        name: Run tests
        command: npm run test
      - persist_to_workspace:
        root: ~/project
        paths:
          - .

workflows:
  my-wordlist-mobile-workflow:
    jobs:
      - test
