version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  run_tests:
    executor:
      name: node/default
      node-version: '19.8.1'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests

workflows:
  my_wordlist_mobile_workflow:
    jobs:
      - run_tests
