version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  run_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - persist_to_workspace:
        root: ~/project
        paths:
          - .

workflows:
  my_wordlist_mobile_workflow:
    jobs:
      - run_tests
