version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:19.8.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests

workflows:
  my_wordlist_mobile_workflow:
    jobs:
      - run_tests
